# TODO: Sort this file to make it more readable
LANG = {
    'en': {
        'exit': 'Exit',
        'new_ticket': 'New ticket',
        'import_db': 'Import database',
        'export_db': 'Export database',
        'current_entries': 'Current entries',
        'date': 'Date',
        'time': 'Time',
        'name': 'Name',
        'surname': 'Surname',
        'phone': 'Phone',
        'email': 'Email',
        'description': 'Description',
        'status': 'Status',
        'edit': 'Edit',
        'delete': 'Delete',
        'save': 'Save',
        'cancel': 'Cancel',
        'save_changes': 'Save changes',
        'cancel_changes': 'Cancel changes',
        'add': 'Add',
        'edit_entry': 'Edit entry',
        'delete_entry': 'Delete entry',
        'add_entry': 'Add entry',
    },
    'pl': {
        'exit': 'Wyjście',
        'new_ticket': 'Nowe zgłoszenie',
        'import_db': 'Importuj bazę danych',
        'export_db': 'Wyeksportuj bazę danych',
        'current_entries': 'Aktualne zgłoszenia',
        'date': 'Data',
        'time': 'Godzina',
        'name': 'Imię',
        'surname': 'Nazwisko',
        'phone': 'Telefon',
        'email': 'Email',
        'description': 'Opis',
        'status': 'Status',
        'edit': 'Edytuj',
        'delete': 'Usuń',
        'save': 'Zapisz',
        'cancel': 'Anuluj',
        'save_changes': 'Zapisz zmiany',
        'cancel_changes': 'Anuluj zmiany',
        'add': 'Dodaj',
        'edit_entry': 'Edytuj zgłoszenie',
        'edit_ticket': 'Okno edycji zgłoszenia',
        'date_modification': 'Modyfikacji',
        'date_creation': 'Utworzenia',
        'delete_entry': 'Usuń zgłoszenie',
        'edit_entry_text': 'Edytujesz zgłoszenie o numerze: ',
        'delete_entry_text': 'Czy na pewno chcesz usunąć zgłoszenie o numerze: ',
        'notes': 'Uwagi',
        'add_note': 'Dodaj notatkę',
        'edit_note': 'Edytuj notatkę',
        'delete_note': 'Usuń notatkę',
        'edit_note_text': 'Edytujesz notatkę o numerze: ',
        'file': 'Plik',
        'car': 'Pojazd',
        'vin': 'VIN',
        'id': 'ID',
        'customer': 'Klient',
        'ticket': 'Zgłoszenie',
        'tickets': 'Zgłoszenia',
        'cars': 'Pojazdy',
        'customers': 'Klienci',
        'first_name': 'Imię',
        'last_name': 'Nazwisko',
        'brand': 'Marka',
        'model': 'Model',
        'year': 'Rok',
        'color': 'Kolor',
        'black': 'Czarny',
        'white': 'Biały',
        'red': 'Czerwony',
        'blue': 'Niebieski',
        'green': 'Zielony',
        'yellow': 'Żółty',
        'orange': 'Pomarańczowy',
        'silver': 'Srebrny',
        'gold': 'Złoty',
        'grey': 'Szary',
        'brown': 'Brązowy',
        'purple': 'Fioletowy',
        'other': 'Inny',
        'ticket_id': 'ID',
        'customer_id': 'Klient',
        'cari_d': 'Pojazd',
        'brand_name': 'Marka',
        'model_name': 'Model',
        'color_name': 'Kolor',
        'customer_exists': 'Klient istnieje w bazie danych, ale podane dane są uzupełniające.'
                           'Czy chcesz je zaktualizować?',
        'customer_exists_title': 'Klient istnieje',
        'error': 'Błąd',
        'empty_last_name': 'Nazwisko nie może być puste.',
        'empty_phone': 'Telefon nie może być pusty.',
        'empty_brand': 'Marka nie może być pusta.',
        'empty_model': 'Model nie może być pusty.',
        'error_loading_gui': 'Wystąpił błąd podczas ładowania okna głównego.',
        'error_loading_window_ticket': 'Wystąpił błąd podczas ładowania okna zgłoszenia.',
        'field_required': 'Pole jest wymagane.',
        'vin_invalid': 'Wymagane 17 znaków',
        'email_invalid': 'Niepoprawny adres email',
        'year_invalid': 'Niepoprawny rok',
        'last_name_invalid': 'Nazwisko w niepoprawnym formacie',
        'phone_invalid': 'Numer błędny e.g. 123456789',
        'brand_name_invalid': 'Nazwa marki niepoprawna',
        'customer_first_name': 'Imię',
        'customer_last_name': 'Nazwisko',
        'debug': 'Debug',
        'cr_customer_window': 'Okno klienta',
        'cr_car_window': 'Okno pojazdu',
        'car_list': 'Lista pojazdów',
        'owner': 'Właściciel',
        'edit_car': 'Edytuj pojazd',
        'edit_customer': 'Edytuj klienta',
        'not_implemented': 'Funkcja nie została jeszcze zaimplementowana.',
        'ask_exit': 'Czy na pewno chcesz wyjść?',
        'ask_add_car': 'Czy chcesz dodać nowy pojazd?',
        'delete_item_warning': 'Czy na pewno chcesz usunąć ten element?',
        'delete_item': 'Usuń element',
        'change_status': 'Zmień status',
        'settings': 'Opcje'
    }
}
