LANG = {
    'en': {
    },
    'pl': {
        'exit': 'Wyjście',
        'new_ticket': 'Nowe zgłoszenie',
        'import_db': 'Importuj bazę danych',
        'export_db': 'Wyeksportuj bazę danych',
        'current_entries': 'Aktualne zgłoszenia',
        'date': 'Data',
        'time': 'Godzina',
        'name': 'Imię',
        'surname': 'Nazwisko',
        'phone': 'Telefon',
        'email': 'Email',
        'description': 'Opis',
        'status': 'Status',
        'edit': 'Edytuj',
        'delete': 'Usuń',
        'save': 'Zapisz',
        'cancel': 'Anuluj',
        'save_changes': 'Zapisz zmiany',
        'cancel_changes': 'Anuluj zmiany',
        'add': 'Dodaj',
        'edit_entry': 'Edytuj zgłoszenie',
        'delete_entry': 'Usuń zgłoszenie',
        'edit_entry_text': 'Edytujesz zgłoszenie o numerze: ',
        'delete_entry_text': 'Czy na pewno chcesz usunąć zgłoszenie o numerze: ',
        'notes': 'Uwagi',
        'add_note': 'Dodaj notatkę',
        'edit_note': 'Edytuj notatkę',
        'delete_note': 'Usuń notatkę',
        'edit_note_text': 'Edytujesz notatkę o numerze: ',
        'file': 'Plik',
        'car': 'Auto',
        'vin': 'VIN',
        'id': 'ID',
    }
}
