name: Compile Python code for Zortech

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      FILENAME: "ZORTECH"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller zortech.spec
      shell: cmd

    - name: Check if executable was created
      run: |
        if not exist .\dist\zortech\${{ env.FILENAME }}.exe (
          echo "Executable file not found."
          exit 1
        )
      shell: cmd

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILENAME }}.exe
        path: dist/zortech/${{ env.FILENAME }}.exe

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile main.py

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: dist/*
