name: Compile Python code for Zortech

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      FILENAME: "ZORTECH"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller --onefile --name ${{ env.FILENAME }} main.py
      shell: cmd

    - name: Check if executable was created
      run: |
        if not exist .\dist\${{ env.FILENAME }}.exe (
          echo "Executable file not found."
          exit 1
        )
      shell: cmd

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILENAME }}.exe
        path: dist/${{ env.FILENAME }}.exe
