name: Compile Python code for Zortech

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    env:
      FILENAME: "zortech"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: pyinstaller zortech.spec
      shell: cmd

    - name: Check if executable was created
      run: |
        if not exist .\dist\${{ env.FILENAME }}\${{ env.FILENAME }}.exe (
          echo "Executable file not found."
          exit 1
        )
      shell: cmd

    - name: Create archive of the application and database
      run: |
        cd dist/${{ env.FILENAME }}
        7z a -r ../${{ env.FILENAME }}-full.zip ./${{ env.FILENAME }}.exe ./_internal/database/

    - name: Upload the full package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILENAME }}-full.zip
        path: dist/${{ env.FILENAME }}-full.zip
